### ISSUE TITLE
fPIC option is not working / not working as expected

### ISSUE THREAD

**Issue by uukhas** [conan-hep/conan-collier#1]
When I specify  `COLLIER:fPIC=True`after `[options]` inside `conanfile.txt`, then I still get 

```
Using Fortran compiler: gfortran
Build type: Release
Collier:  Fortran compiler  = gfortran
          Fortran flags    = -Dcollierdd -DSING \
                                      -ffixed-line-length-132  \
                                      -fno-default-integer-8 -O2 \
                                      -funroll-loops -ffast-math -Wtabs
```

during conan evaluation.

With manual installation to fix this I add `-fPIC` to line `Fortran_FLAGS =` in a file `COLLIER-x.y.z/build/CMakeFiles/collier.dir/flags.make` before evaluation of `make` command.

Can this be achieved in a normal way by `conan`?

P.S. This question is related to the implementation of `COLLIER` inside `FlexibleSUSY` and the only thing which is not working for me is `-fPIC` flag (for `static` option set to `False`).

**Comment by Expander** [comment]
Many thanks for the report!

I've fixed it and checked that `-fPIC` is correctly used during compilation. However, it seems that `cmake` does not add `-fPIC` to `FFLAGS`, but to some other build variable. I.e., `-fPIC` does not appear in the output you've shown.
